### PR TITLE
Small fix, sorry

### PR DESCRIPTION
**Pull request by skyleter**

### CODE REVIEW

**Comment by makandz** [comment]
lol no problem!

**Comment by skyleter** [comment]
Dude, how i can set SMTP to send mail activation or that? .... Sorry i cant figure it. Btw i recommend you to use Pear Mail library.. thx {it allows you to use gmail, well, any SMTP such as yahoo or a custom one}, thx.

**Comment by makandz** [comment]
The SMTP mailing thing is broken for sure. I tried playing around with it a while ago, but couldn't get it to work. I have recently trying to do it but never really had time to do it since I was so caught up with the Cigar project :(

**Comment by skyleter** [comment]
Are you using php 5.4 ~ 5.6 ?

Php 7.0 removes many things such as mysql_query(); and that things [really annoying], i had to switch from it to 5.6 because of that.

Btw, here's the library: http://download.pear.php.net/package/Mail-1.3.0.tgz

I will test it right now to see if works for me

**Comment by skyleter** [comment]
It works. http://prntscr.com/a7xbuh && http://prntscr.com/a7xbzp

Here's the code i got from StackOverflow

```
<?php
// Pear Mail Library
require_once "Mail.php";

$from = '<cpfpantera@gmail.com>'; 
$to = '<mogok1penguin@gmail.com>'; // You're good at coding, you can edit it to make it send to the user email
$subject = 'Hi!';
$body = "Hi,\n\nHow are you? ALLAHU AKBAR";

$headers = array(
    'From' => $from,
    'To' => $to,
    'Subject' => $subject
);

$smtp = Mail::factory('smtp', array(
        'host' => 'ssl://smtp.gmail.com',
        'port' => '465',
        'auth' => true,
        'username' => 'cpfpantera@gmail.com',
        'password' => 'PASSWORDDVHDFGHDS'
    ));

$mail = $smtp->send($to, $headers, $body);

if (PEAR::isError($mail)) {
    echo('<p>' . $mail->getMessage() . '</p>');
} else {
    echo('<p>Message successfully sent!</p>');
}

?>


```

**Comment by skyleter** [comment]
Can you get in skype ? Or discord link : https://discord.gg/0oRD2Kx3IWt5tu9D

**Pull request merged**
